package view;

/**
 *
 * @author kneretin
 */
public class MainViewStringFXML {

    public static final String FXML
            = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "\n"
            + "<?import javafx.scene.effect.*?>\n"
            + "<?import javafx.geometry.*?>\n"
            + "<?import javafx.scene.text.*?>\n"
            + "<?import java.lang.*?>\n"
            + "<?import java.util.*?>\n"
            + "<?import javafx.scene.*?>\n"
            + "<?import javafx.scene.control.*?>\n"
            + "<?import javafx.scene.layout.*?>\n"
            + "\n"
            + "<AnchorPane id=\"AnchorPane\" prefHeight=\"635.0\" prefWidth=\"415.0\" xmlns=\"http://javafx.com/javafx/8\" xmlns:fx=\"http://javafx.com/fxml/1\" fx:controller=\"controller.MainController\">\n"
            + "   <children>\n"
            + "      <MenuBar prefHeight=\"25.0\" prefWidth=\"415.0\">\n"
            + "        <menus>\n"
            + "          <Menu mnemonicParsing=\"false\" text=\"Файл\">\n"
            + "            <items>\n"
            + "              <MenuItem mnemonicParsing=\"false\" text=\"Файлы ПФР\" />\n"
            + "                  <MenuItem mnemonicParsing=\"false\" text=\"Каталог выгрузки\" />\n"
            + "                  <MenuItem mnemonicParsing=\"false\" text=\"Выход\" />\n"
            + "            </items>\n"
            + "          </Menu>\n"
            + "          <Menu mnemonicParsing=\"false\" text=\"Режимы\" />\n"
            + "          <Menu mnemonicParsing=\"false\" text=\"Справка\">\n"
            + "            <items>\n"
            + "              <MenuItem fx:id=\"versionMenuItem\" mnemonicParsing=\"false\" text=\"Версия\" />\n"
            + "            </items>\n"
            + "          </Menu>\n"
            + "        </menus>\n"
            + "      </MenuBar>\n"
            + "      <TitledPane animated=\"false\" collapsible=\"false\" layoutY=\"25.0\" prefHeight=\"440.0\" prefWidth=\"415.0\" style=\"-fx-text-alignment: center;\" text=\"Установки\" textAlignment=\"CENTER\">\n"
            + "        <content>\n"
            + "          <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"406.0\" prefWidth=\"413.0\">\n"
            + "               <children>\n"
            + "                  <Label layoutX=\"14.0\" layoutY=\"14.0\" prefHeight=\"25.0\" prefWidth=\"386.0\" text=\"Директория, содержащая файлы ПФР\" />\n"
            + "                  <Button fx:id=\"IN_FILES_DIRECTORY_DIALOG\" layoutX=\"360.0\" layoutY=\"39.0\" mnemonicParsing=\"false\" prefHeight=\"29.0\" prefWidth=\"44.0\" text=\"...\" />\n"
            + "                  <Button fx:id=\"OUT_FILES_DIRECTORY_DIALOG\" layoutX=\"361.0\" layoutY=\"93.0\" mnemonicParsing=\"false\" prefHeight=\"29.0\" prefWidth=\"43.0\" text=\"...\" />\n"
            + "                  <Label layoutX=\"15.0\" layoutY=\"68.0\" prefHeight=\"25.0\" prefWidth=\"386.0\" text=\"Директория для выгрузки СВОДа\" />\n"
            + "                  <Button fx:id=\"SETTINGS_BUTTON\" layoutX=\"14.0\" layoutY=\"141.0\" mnemonicParsing=\"false\" prefHeight=\"29.0\" prefWidth=\"144.0\" text=\"Параметры\" />\n"
            + "                  <Button fx:id=\"KBK_BUTTON\" layoutX=\"234.0\" layoutY=\"141.0\" mnemonicParsing=\"false\" prefHeight=\"29.0\" prefWidth=\"171.0\" text=\"Классификатор строк\" />\n"
            + "                  <TitledPane animated=\"false\" collapsible=\"false\" layoutX=\"11.0\" layoutY=\"189.0\" prefHeight=\"203.0\" prefWidth=\"395.0\" text=\"Дополнительные опции\" wrapText=\"true\">\n"
            + "                    <content>\n"
            + "                      <AnchorPane focusTraversable=\"true\" minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"164.0\" prefWidth=\"387.0\">\n"
            + "                           <children>\n"
            + "                              <CheckBox fx:id=\"makeFoldersCheckBox\" layoutX=\"14.0\" layoutY=\"14.0\" mnemonicParsing=\"false\" prefHeight=\"25.0\" prefWidth=\"17.0\" style=\"-fx-background-color: white;\" />\n"
            + "                              <TextField fx:id=\"outFileNumberText\" layoutX=\"4.0\" layoutY=\"75.0\" prefHeight=\"29.0\" prefWidth=\"35.0\" />\n"
            + "                              <TextArea fx:id=\"notEditable2\" editable=\"false\" focusTraversable=\"false\" layoutX=\"45.0\" layoutY=\"65.0\" prefHeight=\"47.0\" prefWidth=\"329.0\" text=\"Порядковый номер сводного&#10; файла данных за текущую дату\">\n"
            + "                              </TextArea>\n"
            + "                              \n"
            + "                              <TextArea fx:id=\"notEditable3\" editable=\"false\" layoutX=\"126.0\" layoutY=\"121.0\" prefHeight=\"25.0\" prefWidth=\"248.0\" text=\"Текущий номер сводной ведомости\" />\n"
            + "                              <TextField fx:id=\"currentNumber\" layoutX=\"14.0\" layoutY=\"119.0\" prefHeight=\"29.0\" prefWidth=\"90.0\" />\n"
            + "                              <TextArea fx:id=\"notEditable1\" editable=\"false\" focusTraversable=\"false\" layoutX=\"45.0\" layoutY=\"14.0\" prefHeight=\"47.0\" prefWidth=\"329.0\" text=\"При выгрузке создавать подкаталог для &#10;каждой ведомости\">\n"
            + "                                 \n"
            + "                              </TextArea>\n"
            + "                           </children>\n"
            + "                        </AnchorPane>\n"
            + "                    </content>\n"
            + "                     <font>\n"
            + "                        <Font size=\"16.0\" />\n"
            + "                     </font>\n"
            + "                  </TitledPane>\n"
            + "                  <TextField fx:id=\"inFilesDirectoryName\" layoutX=\"12.0\" layoutY=\"39.0\" prefHeight=\"29.0\" prefWidth=\"344.0\" />\n"
            + "                  <TextField fx:id=\"outFilesDirectoryName\" layoutX=\"13.0\" layoutY=\"93.0\" prefHeight=\"29.0\" prefWidth=\"343.0\" />\n"
            + "               </children>\n"
            + "            </AnchorPane>\n"
            + "        </content>\n"
            + "         <font>\n"
            + "            <Font size=\"18.0\" />\n"
            + "         </font>\n"
            + "      </TitledPane>\n"
            + "      <ComboBox fx:id=\"selectFormComboBox\" layoutX=\"10.0\" layoutY=\"535.0\" prefHeight=\"25.0\" prefWidth=\"395.0\" style=\"-fx-text-alignment: center;\" />\n"
            + "      <TextArea fx:id=\"notEditable4\" editable=\"false\" layoutX=\"9.0\" layoutY=\"474.0\" prefHeight=\"47.0\" prefWidth=\"395.0\" style=\"-fx-text-alignment: center;\" text=\"Ведомость 1С для корректировок и&#10; формирования сводной таблицы\">\n"
            + "         <font>\n"
            + "            <Font size=\"14.0\" />\n"
            + "         </font>\n"
            + "         <opaqueInsets>\n"
            + "            <Insets />\n"
            + "         </opaqueInsets>\n"
            + "      </TextArea>\n"
            + "      <Button fx:id=\"LOADDATA_BUTTON\" layoutX=\"9.0\" layoutY=\"590.0\" mnemonicParsing=\"false\" prefHeight=\"25.0\" prefWidth=\"395.0\" text=\"ЗАГРУЗИТЬ ДАННЫЕ\">\n"
            + "         <font>\n"
            + "            <Font size=\"14.0\" />\n"
            + "         </font>\n"
            + "      </Button>\n"
            + "   </children>\n"
            + "</AnchorPane>\n";

}
