package view;

/**
 *
 * @author kneretin
 */
public class SettingsViewStringFXML {

    public static final String FXML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "\n"
            + "<?import javafx.scene.effect.*?>\n"
            + "<?import javafx.geometry.*?>\n"
            + "<?import javafx.scene.text.*?>\n"
            + "<?import java.lang.*?>\n"
            + "<?import java.util.*?>\n"
            + "<?import javafx.scene.*?>\n"
            + "<?import javafx.scene.control.*?>\n"
            + "<?import javafx.scene.layout.*?>\n"
            + "\n"
            + "<AnchorPane id=\"AnchorPane\" prefHeight=\"761.0\" prefWidth=\"555.0\" xmlns=\"http://javafx.com/javafx/8\" xmlns:fx=\"http://javafx.com/fxml/1\" fx:controller=\"controller.SettingsController\">\n"
            + "    <children>\n"
            + "        <TitledPane animated=\"false\" collapsible=\"false\" prefHeight=\"759.0\" prefWidth=\"553.0\" style=\"-fx-text-alignment: center;\" text=\"Параметры выгрузки в СВОД\" textAlignment=\"CENTER\">\n"
            + "            <content>\n"
            + "                <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"716.0\" prefWidth=\"553.0\">\n"
            + "                    <children>\n"
            + "                        <TitledPane animated=\"false\" prefHeight=\"133.0\" prefWidth=\"549.0\" text=\"Регистрационный номер организации, подготовившей информацию\">\n"
            + "                            <content>\n"
            + "                                <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"103.0\" prefWidth=\"518.0\">\n"
            + "                                    <children>\n"
            + "                                        <Label layoutX=\"20.0\" layoutY=\"12.0\" prefHeight=\"27.0\" prefWidth=\"100.0\" text=\"Код региона\" />\n"
            + "                                        <TextField fx:id=\"region_field\" layoutX=\"119.0\" layoutY=\"14.0\" prefHeight=\"27.0\" prefWidth=\"99.0\" />\n"
            + "                                        <Label layoutX=\"20.0\" layoutY=\"55.0\" prefHeight=\"30.0\" prefWidth=\"100.0\" text=\"Код района\" />\n"
            + "                                        <TextField fx:id=\"raion_field\" layoutX=\"119.0\" layoutY=\"57.0\" prefHeight=\"27.0\" prefWidth=\"100.0\" />\n"
            + "                                        <TextField fx:id=\"regnumberPFR_field\" layoutX=\"231.0\" layoutY=\"56.0\" prefHeight=\"27.0\" prefWidth=\"253.0\" />\n"
            + "                                        <Label layoutX=\"231.0\" layoutY=\"13.0\" prefHeight=\"30.0\" prefWidth=\"254.0\" text=\"Регистрационный номер в ПФР\" textAlignment=\"RIGHT\" />\n"
            + "                                    </children>\n"
            + "                                </AnchorPane>\n"
            + "                            </content>\n"
            + "                        </TitledPane>\n"
            + "                        <TitledPane animated=\"false\" layoutY=\"133.0\" prefHeight=\"111.0\" prefWidth=\"550.0\" text=\"Наименование организации, подготовившей информацию (учреждение)\">\n"
            + "                            <content>\n"
            + "                                <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"81.0\" prefWidth=\"541.0\">\n"
            + "                                    <children>\n"
            + "                                        <TextArea fx:id=\"ORGname_area\" layoutX=\"10.0\" layoutY=\"10.0\" prefHeight=\"60.0\" prefWidth=\"485.0\" />\n"
            + "                                    </children>\n"
            + "                                </AnchorPane>\n"
            + "                            </content>\n"
            + "                        </TitledPane>\n"
            + "                        <TitledPane animated=\"false\" layoutY=\"244.0\" prefHeight=\"165.0\" prefWidth=\"550.0\" text=\"Коды (КТО ПФР,ОКПО,КСП,ОКЕИ)\">\n"
            + "                            <content>\n"
            + "                                <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"169.0\" prefWidth=\"433.0\">\n"
            + "                                    <children>\n"
            + "                                        <TextField fx:id=\"KTOPFR_field\" layoutX=\"91.0\" layoutY=\"16.0\" />\n"
            + "                                        <Label contentDisplay=\"CENTER\" layoutX=\"21.0\" layoutY=\"18.0\" prefHeight=\"24.0\" prefWidth=\"70.0\" text=\"КТО ПФР\" textAlignment=\"CENTER\" />\n"
            + "                                        <Label contentDisplay=\"CENTER\" layoutX=\"23.0\" layoutY=\"57.0\" prefHeight=\"24.0\" prefWidth=\"68.0\" text=\"ОКПО\" textAlignment=\"CENTER\" />\n"
            + "                                        <TextField fx:id=\"OKPO_field\" layoutX=\"91.0\" layoutY=\"55.0\" />\n"
            + "                                        <TextField fx:id=\"KSP_field\" layoutX=\"91.0\" layoutY=\"94.0\" />\n"
            + "                                        <Label contentDisplay=\"CENTER\" layoutX=\"28.0\" layoutY=\"96.0\" prefHeight=\"24.0\" prefWidth=\"63.0\" text=\"КСП\" textAlignment=\"CENTER\" />\n"
            + "                                        <Label alignment=\"CENTER\" contentDisplay=\"CENTER\" layoutX=\"317.0\" layoutY=\"16.0\" prefHeight=\"24.0\" prefWidth=\"47.0\" text=\"ОКЕИ\" textAlignment=\"CENTER\" />\n"
            + "                                        <TextField fx:id=\"OKEI_field\" layoutX=\"364.0\" layoutY=\"14.0\" prefHeight=\"29.0\" prefWidth=\"71.0\" />\n"
            + "                                    </children>\n"
            + "                                </AnchorPane>\n"
            + "                            </content>\n"
            + "                        </TitledPane>\n"
            + "                        <TitledPane animated=\"false\" layoutX=\"-1.0\" layoutY=\"409.0\" prefHeight=\"120.0\" prefWidth=\"551.0\" text=\"Наименование структурного подразделения, подготовившего информацию\">\n"
            + "                            <content>\n"
            + "                                <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"180.0\" prefWidth=\"200.0\">\n"
            + "                                    <children>\n"
            + "                                        <TextArea fx:id=\"STRUCTname_area\" layoutX=\"14.0\" layoutY=\"14.0\" prefHeight=\"68.0\" prefWidth=\"482.0\" />\n"
            + "                                    </children>\n"
            + "                                </AnchorPane>\n"
            + "                            </content>\n"
            + "                        </TitledPane>\n"
            + "                        <TitledPane animated=\"false\" layoutY=\"529.0\" prefHeight=\"139.0\" prefWidth=\"550.0\" text=\"Примечание (указывается служебная информация, например, имя передаваемого файла)\">\n"
            + "                            <content>\n"
            + "                                <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"169.0\" prefWidth=\"411.0\">\n"
            + "                                    <children>\n"
            + "                                        <RadioButton fx:id=\"rgroup_empty_rbutton\" layoutX=\"14.0\" layoutY=\"11.0\" mnemonicParsing=\"false\" prefHeight=\"24.0\" prefWidth=\"182.0\" text=\"Пустое поле\" />\n"
            + "                                        <RadioButton fx:id=\"rgroup_name_rbutton\" layoutX=\"14.0\" layoutY=\"39.0\" mnemonicParsing=\"false\" prefHeight=\"24.0\" prefWidth=\"182.0\" text=\"Имя файла данных\" />\n"
            + "                                        <RadioButton fx:id=\"rgroup_else_rbutton\" layoutX=\"15.0\" layoutY=\"69.0\" mnemonicParsing=\"false\" prefHeight=\"24.0\" prefWidth=\"182.0\" text=\"Иная информация\" />\n"
            + "                                        <TextField fx:id=\"rgroup_else_field\" layoutX=\"206.0\" layoutY=\"67.0\" prefHeight=\"29.0\" prefWidth=\"278.0\" />\n"
            + "                                    </children>\n"
            + "                                </AnchorPane>\n"
            + "                            </content>\n"
            + "                        </TitledPane>\n"
            + "                        <Button fx:id=\"save_button\" layoutX=\"34.0\" layoutY=\"681.0\" mnemonicParsing=\"false\" prefHeight=\"29.0\" prefWidth=\"180.0\" text=\"Сохранить\" />\n"
            + "                        <Button fx:id=\"close_button\" layoutX=\"324.0\" layoutY=\"681.0\" mnemonicParsing=\"false\" prefHeight=\"29.0\" prefWidth=\"180.0\" text=\"Закрыть\" />\n"
            + "                    </children>\n"
            + "                </AnchorPane>\n"
            + "            </content>\n"
            + "        </TitledPane>\n"
            + "    </children>\n"
            + "</AnchorPane>\n";
}
